# configs/brand_ranges.yaml
# One‑line brand summaries based on USL FINAL REPORT.pdf :contentReference[oaicite:0]{index=0}&#8203;:contentReference[oaicite:1]{index=1}

axe:          "Axe offers men’s grooming products celebrating confidence and self‑expression."
ayush:        "Lever Ayush combines 5,000 years of Ayurvedic wisdom with modern care for skin, hair, and body."
clear:        "Clear delivers science‑backed anti‑dandruff haircare for men of all ages."
comfort:      "Comfort provides fabric softeners that keep clothing soft, fresh, and long‑lasting."
closeup:      "Closeup offers oral care products emphasizing fresh breath and confidence for young adults."
domex:        "Domex supplies powerful toilet and bathroom cleaners for a hygienic living environment."
dove:         "Dove delivers gentle skincare and haircare solutions that promote real beauty and nourishment."
glowhandsome: "Glow & Handsome is a men’s skincare line enhancing skin radiance and attractiveness."
glowyourself: "Glow & Lovely (now Glow & Lovely) provides skincare for a healthy, glowing complexion."
horlicks:     "Horlicks offers malted‑milk drinks packed with nutrients for growing children and families."
knorr:        "Knorr brings soups, stocks, sauces, and seasonings that elevate home‑cooked meals."
lux:          "Lux offers indulgent beauty soaps and body washes for a luxurious skincare experience."
lakme:        "Lakmé provides innovative cosmetics and skincare for self‑expression and vibrant beauty."
lifebuoy:     "Lifebuoy delivers germ‑protecting soaps and handwashes for families’ daily hygiene."
marmite:      "Marmite is a yeast‑extract spread known for its bold, distinctive savory flavor."
pears:        "Pears offers gentle skincare and baby‑care products for sensitive skin and nurturing care."
ponds:        "Pond’s provides skincare that treats skin as an investment—moisturizers, cleansers & masks."
pureit:       "Pureit delivers convenient water purification systems for safe, healthy drinking water."
rexona:       "Rexona offers deodorants and antiperspirants that provide reliable protection against sweat."
rin:          "Rin provides laundry detergents designed for effective stain removal and fabric care."
signal:       "Signal delivers toothpaste and oral care products for healthy teeth and confident smiles."
sunlight:     "Sunlight offers household cleaning solutions that tackle dirt and grime with ease."
sunsilk:      "Sunsilk’s haircare range provides vibrant shampoos and conditioners for various hair needs."
surf_excel:   "Surf Excel promotes resilient laundry care with powerful stain‑removal and fabric protection."
tresemme:     "TRESemmé delivers salon‑quality haircare solutions for confident styling at home."
vaseline:     "Vaseline provides protective and restorative skincare to maintain healthy moisture barriers."
vim:          "Vim offers multi‑surface cleaners that remove tough stains and grease with a refreshing scent."
viva:         "Viva delivers tea blends crafted to enhance the tea‑drinking experience for local tastes."
ufs:          "UFS offers dairy‑based desserts and snacks for everyday indulgence."
unilever:     "Unilever encapsulates a diverse portfolio of brands under shared corporate values."
