tone: formal
prohibited_phrases:
  - "cheap"
  - "guaranteed results"
  - "fake"
  - "cheap"
guidelines:
  - "Always use respectful tone"
  - "Use product claims supported by data"
  - "Use respectful language"
  - "Avoid unsupported health claims"
